// src/agentHooks/opencodePlugin.ts — The OpenCode plugin AnyWhere Terminal
// drops into a configuration directory of its own.
//
// Source rather than a module: OpenCode loads a plugin from disk with its own
// runtime, so this file is never imported by the extension — it is written out
// by `opencodeConfigDir.ts` and read back by OpenCode.
//
// The plugin reports identity and nothing else, and reports it once per
// session: OpenCode emits an event per message part, and a POST per part would
// be a flood on a socket that only ever needed to hear a session id.
//
// See: asimov/changes/agent-session-hook-identity/design.md D2, D6.

/** Bumped whenever the source changes, so a stale file on disk is replaced. */
export const OPENCODE_PLUGIN_VERSION = 2;

/**
 * How long a report may take before the plugin abandons it.
 *
 * The receiver is on loopback, so this is not latency budgeting — it is the
 * one case that would otherwise hang OpenCode's event handler: a peer that
 * accepts the connection and never answers.
 */
export const OPENCODE_REPORT_TIMEOUT_MS = 1000;

export const OPENCODE_PLUGIN_FILE = "anywhere-terminal-identity.ts";

/**
 * The plugin's source.
 *
 * Written verbatim; the only thing it reads from its environment is the URL of
 * the credential issued to the terminal it was started in, so a plugin left
 * behind on disk reports nothing at all.
 */
export function buildOpenCodePluginSource(): string {
  return `// anywhere-terminal identity reporter — v${OPENCODE_PLUGIN_VERSION}
// Generated by AnyWhere Terminal. Reports only the session id of the OpenCode
// session running in this terminal. Safe to delete.

const reported = new Set()

// Only a session event names a session. \`message.updated.properties.info\` is a
// Message, whose \`id\` is a message id — and a session carrying a parentID is a
// task's child, not the session this terminal is on.
function sessionOf(event) {
  if (event?.type !== "session.created" && event?.type !== "session.updated") return undefined
  const info = event.properties?.info
  if (info === undefined || info === null) return event.properties?.sessionID
  return info.parentID === undefined || info.parentID === null ? info.id : undefined
}

async function report(sessionID) {
  const base = process.env.ANYWHERE_TERMINAL_AGENT_HOOK_URL
  if (!base || typeof sessionID !== "string" || sessionID === "" || reported.has(sessionID)) return
  reported.add(sessionID)
  try {
    await fetch(base + "/opencode", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ sessionID }),
      signal: AbortSignal.timeout(${OPENCODE_REPORT_TIMEOUT_MS}),
    })
  } catch {
    // Fail open: a receiver that is gone, or that never answers, must never
    // disturb the session. Forgetting the id leaves the next event free to
    // retry.
    reported.delete(sessionID)
  }
}

export const server = async () => ({
  event: async ({ event }) => {
    await report(sessionOf(event))
  },
})
`;
}
