// src/agentHooks/opencodePlugin.ts — The OpenCode plugin AnyWhere Terminal
// drops into a configuration directory of its own.
//
// Source rather than a module: OpenCode loads a plugin from disk with its own
// runtime, so this file is never imported by the extension — it is written out
// by `opencodeConfigDir.ts` and read back by OpenCode.
//
// The plugin reports identity and nothing else, and reports it once per
// session: OpenCode emits an event per message part, and a POST per part would
// be a flood on a socket that only ever needed to hear a session id.
//
// See: asimov/changes/agent-session-hook-identity/design.md D2, D6.

/** Bumped whenever the source changes, so a stale file on disk is replaced. */
export const OPENCODE_PLUGIN_VERSION = 1;

export const OPENCODE_PLUGIN_FILE = "anywhere-terminal-identity.ts";

/**
 * The plugin's source.
 *
 * Written verbatim; the only thing it reads from its environment is the URL of
 * the credential issued to the terminal it was started in, so a plugin left
 * behind on disk reports nothing at all.
 */
export function buildOpenCodePluginSource(): string {
  return `// anywhere-terminal identity reporter — v${OPENCODE_PLUGIN_VERSION}
// Generated by AnyWhere Terminal. Reports only the session id of the OpenCode
// session running in this terminal. Safe to delete.

const reported = new Set()

async function report(sessionID) {
  const base = process.env.ANYWHERE_TERMINAL_AGENT_HOOK_URL
  if (!base || typeof sessionID !== "string" || sessionID === "" || reported.has(sessionID)) return
  reported.add(sessionID)
  try {
    await fetch(base + "/opencode", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ sessionID }),
    })
  } catch {
    // Fail open: the receiver being gone must never disturb the session.
    reported.delete(sessionID)
  }
}

export const server = async () => ({
  event: async ({ event }) => {
    await report(event?.properties?.sessionID ?? event?.properties?.info?.id)
  },
})
`;
}
